package GUI;

import GUItil.MyUtil;
import com.intellij.uiDesigner.core.GridLayoutManager;

import javax.swing.*;
import java.awt.*;
import java.awt.event.MouseAdapter;

public class TabForm {
    private JPanel panel;
    private int cnt = 0;

    private JMenu menu1, menu2, menu3, menu4, menu5, menu6;

    public TabForm() {
        JMenuBar menuBar = new JMenuBar();
        menuBar.setBackground(panel.getBackground());
        menuBar.setForeground(panel.getBackground());

        menu1 = new JMenu(MyUtil.formatStr("随机生成拓扑仿真", 40));
        menuBar.add(menu1);
        cnt++;

        menu2 = new JMenu(MyUtil.formatStr("格状网络拓扑编队", 40));
        menuBar.add(menu2);
        cnt++;

        menu3 = new JMenu(MyUtil.formatStr("链状网络拓扑编队", 40));
        menuBar.add(menu3);
        cnt++;

        menu4 = new JMenu(MyUtil.formatStr("球状网络拓扑编队", 40));
        menuBar.add(menu4);
        cnt++;

        menu5 = new JMenu(MyUtil.formatStr("编队切换仿真", 40));
        menuBar.add(menu5);
        cnt++;

        menu6 = new JMenu(MyUtil.formatStr("弹性网络仿真", 40));
        menuBar.add(menu6);
        cnt++;

        panel.add(menuBar);

        menu1.addMouseListener(new MouseAdapter() {

        });
        menu2.addMouseListener(new MouseAdapter() {

        });
        menu3.addMouseListener(new MouseAdapter() {

        });
        menu4.addMouseListener(new MouseAdapter() {

        });
        menu5.addMouseListener(new MouseAdapter() {

        });
        menu6.addMouseListener(new MouseAdapter() {

        });
    }

    public JPanel getPanel() {
        return panel;
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
    }
}
